homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

upload_file:
    path:      /upload
    defaults:  { _controller: AppBundle:Default:upload }

image_gallery:
    path:      /gallery
    defaults:  { _controller: AppBundle:Default:gallery }